/**
 * This file was generated by the Jeddict
 */
package entity.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * @author sawad
 */
@Entity
public class CompetitionMatch implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private Integer score1;

    @Basic
    private Integer score2;

    @Basic
    private Integer status;

    @ManyToOne
    private Episode episode;

    @ManyToOne
    private School school1;

    @ManyToOne
    private School school2;

    public CompetitionMatch() {
    }

    
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getScore1() {
        return this.score1;
    }

    public void setScore1(Integer score1) {
        this.score1 = score1;
    }

    public Integer getScore2() {
        return this.score2;
    }

    public void setScore2(Integer score2) {
        this.score2 = score2;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Episode getEpisode() {
        return this.episode;
    }

    public void setEpisode(Episode episode) {
        this.episode = episode;
    }

    public School getSchool1() {
        return this.school1;
    }

    public void setSchool1(School school1) {
        this.school1 = school1;
    }

    public School getSchool2() {
        return this.school2;
    }

    public void setSchool2(School school2) {
        this.school2 = school2;
    }

}