/**
 * This file was generated by the Jeddict
 */
package entity.domain;

import java.io.Serializable;
import java.util.Objects;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class QuestionSubject implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private String question_subject;

    public QuestionSubject() {
    }

    
    public String getQuestion_subject() {
        return this.question_subject;
    }

    public void setQuestion_subject(String question_subject) {
        this.question_subject = question_subject;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 29 * hash + Objects.hashCode(this.question_subject);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final QuestionSubject other = (QuestionSubject) obj;
        if (!Objects.equals(this.question_subject, other.question_subject)) {
            return false;
        }
        return true;
    }

    
    @Override
    public String toString() {
        return question_subject;
    }
    
    

}