/**
 * This file was generated by the Jeddict
 */
package entity.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * @author sawad
 */
@Entity
public class Question implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String content;

    @Basic
    private String hide;

    @Basic
    private String video_image_none;

    @Basic
    private String option1;

    @Basic
    private String option2;

    @Basic
    private String option3;

    @Basic
    private String imageVideoPath;

    @Basic
    private String multipleTrueFalseDirectAnswer;

    @Basic
    private String multipleCorrectAnswer;

    @Basic
    private String trueFalseCorrectAnswer;

    @Basic
    private String directAnswer;

    @ManyToOne
    private Stage stage;

    @ManyToOne
    private QuestionSubject questionSubject;

    @ManyToOne
    private PublicFigure publicFigure;

    @ManyToOne
    private QuestionPoint questionPoint;

    @ManyToOne
    private Episode episode;

    public Question() {
    }

    
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getHide() {
        return this.hide;
    }

    public void setHide(String hide) {
        this.hide = hide;
    }

    public String getVideo_image_none() {
        return this.video_image_none;
    }

    public void setVideo_image_none(String video_image_none) {
        this.video_image_none = video_image_none;
    }

    public String getOption1() {
        return this.option1;
    }

    public void setOption1(String option1) {
        this.option1 = option1;
    }

    public String getOption2() {
        return this.option2;
    }

    public void setOption2(String option2) {
        this.option2 = option2;
    }

    public String getOption3() {
        return this.option3;
    }

    public void setOption3(String option3) {
        this.option3 = option3;
    }

    public String getImageVideoPath() {
        return this.imageVideoPath;
    }

    public void setImageVideoPath(String imageVideoPath) {
        this.imageVideoPath = imageVideoPath;
    }

    public String getMultipleTrueFalseDirectAnswer() {
        return this.multipleTrueFalseDirectAnswer;
    }

    public void setMultipleTrueFalseDirectAnswer(String multipleTrueFalseDirectAnswer) {
        this.multipleTrueFalseDirectAnswer = multipleTrueFalseDirectAnswer;
    }

    public String getMultipleCorrectAnswer() {
        return this.multipleCorrectAnswer;
    }

    public void setMultipleCorrectAnswer(String multipleCorrectAnswer) {
        this.multipleCorrectAnswer = multipleCorrectAnswer;
    }

    public String getTrueFalseCorrectAnswer() {
        return this.trueFalseCorrectAnswer;
    }

    public void setTrueFalseCorrectAnswer(String trueFalseCorrectAnswer) {
        this.trueFalseCorrectAnswer = trueFalseCorrectAnswer;
    }

    public String getDirectAnswer() {
        return this.directAnswer;
    }

    public void setDirectAnswer(String directAnswer) {
        this.directAnswer = directAnswer;
    }

    public Stage getStage() {
        return this.stage;
    }

    public void setStage(Stage stage) {
        this.stage = stage;
    }

    public QuestionSubject getQuestionSubject() {
        return this.questionSubject;
    }

    public void setQuestionSubject(QuestionSubject questionSubject) {
        this.questionSubject = questionSubject;
    }

    public PublicFigure getPublicFigure() {
        return this.publicFigure;
    }

    public void setPublicFigure(PublicFigure publicFigure) {
        this.publicFigure = publicFigure;
    }

    public QuestionPoint getQuestionPoint() {
        return this.questionPoint;
    }

    public void setQuestionPoint(QuestionPoint questionPoint) {
        this.questionPoint = questionPoint;
    }

    public Episode getEpisode() {
        return this.episode;
    }

    public void setEpisode(Episode episode) {
        this.episode = episode;
    }

}